# Análise Exploratória

### Importação das bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Carregando os Dados Brutos

In [176]:
nome_arquivo_bruto = "../data/raw/BASE DE DADOS PEDE 2024 - DATATHON.xlsx"

# identificado o nome das planilhas no arquivo
arquivo = pd.ExcelFile(nome_arquivo_bruto)
print(arquivo.sheet_names)

['PEDE2022', 'PEDE2023', 'PEDE2024']

In [245]:
# verificando a estrutura das planilhas
for sheet in arquivo.sheet_names:
     print("Arquivo:", sheet, "Estrutura:",  pd.read_excel(nome_arquivo_bruto, sheet_name=sheet).shape)

Arquivo: PEDE2022 Estrutura: (860, 42)
Arquivo: PEDE2023 Estrutura: (1014, 48)
Arquivo: PEDE2024 Estrutura: (1156, 50)

In [247]:
# criando os datasets
df_pede_22 = pd.read_excel(nome_arquivo_bruto, sheet_name="PEDE2022")
df_pede_23 = pd.read_excel(nome_arquivo_bruto, sheet_name="PEDE2023")
df_pede_24 = pd.read_excel(nome_arquivo_bruto, sheet_name="PEDE2024")

# atribuindo a identificação do ano de referência
df_pede_22['ano_referencia'] = 2022
df_pede_23['ano_referencia'] = 2023
df_pede_24['ano_referencia'] = 2024

In [248]:
colunas_remover = ['Turma',
                   'Nome',
                   'Nome Anonimizado',
                   'Ano nasc',
                   'Data de Nasc',
                   'Ano ingresso',
                   'Instituição de ensino',
                   'Nº Av',
                   'Avaliador1',
                   'Avaliador2',
                   'Avaliador3',
                   'Avaliador4',
                   'Avaliador5',
                   'Avaliador6',
                   'Destaque IEG',
                   'Destaque IDA',
                   'Destaque IPV',
                   'Destaque IPV.1',
                   'Atingiu PV',
                   'Escola',
                   'Ativo/ Inativo',
                   'Ativo/ Inativo.1',
                   'Rec Psicologia',
                   'Rec Av1',
                   'Rec Av2',
                   'Rec Av3',
                   'Rec Av4']

In [265]:
mapping = {    
    "idade": ["idade", "idade 22"],
    "defasagem": ["defas", "defasagem"],    
    "nota_ingles": ["ing", "inglês"],
    "nota_matematica": ["mat", "matem"],
    "nota_portugues": ["por", "portug"],
    "genero":["gênero"],
    "fase_atual":["fase"],    
    "fase_ideal":["fase ideal"],
    "indicado_bolsa":["indicado"]
}

def normalizar_colunas(df, mapping):
    col_rename = {}
    
    for padrao, variacoes in mapping.items():
        for col in variacoes:
            if col in df.columns:
                col_rename[col] = padrao
                
    return df.rename(columns=col_rename)

In [266]:
df_pede_22.drop(columns=colunas_remover, inplace=True, errors='ignore')
df_pede_23.drop(columns=colunas_remover, inplace=True, errors='ignore')
df_pede_24.drop(columns=colunas_remover, inplace=True, errors='ignore')

df_pede_22.columns = df_pede_22.columns.str.lower()
df_pede_23.columns = df_pede_23.columns.str.lower()
df_pede_24.columns = df_pede_24.columns.str.lower()

df_pede_22 = normalizar_colunas(df_pede_22, mapping)
df_pede_23 = normalizar_colunas(df_pede_23, mapping)
df_pede_24 = normalizar_colunas(df_pede_24, mapping)

In [ ]:
# remover 'pedra 23' no df_pede_23

In [272]:
df_pede_23.drop(columns=colunas_remover, errors="ignore").columns

Index(['ra', 'fase_atual', 'inde 2023', 'pedra 2023', 'idade', 'genero',
       'pedra 20', 'pedra 21', 'pedra 22', 'pedra 23', 'inde 22', 'inde 23',
       'cg', 'cf', 'ct', 'iaa', 'ieg', 'ips', 'ipp', 'ida', 'nota_matematica',
       'nota_portugues', 'nota_ingles', 'indicado_bolsa', 'ipv', 'ian',
       'fase_ideal', 'defasagem', 'ano_referencia'],
      dtype='object')

In [280]:
cols_22 = ['ra', 'fase_atual', 'idade', 'genero', 'pedra 20', 'pedra 21', 'pedra 22',             'inde 22',            'ano_referencia']
cols_23 = ['ra', 'fase_atual', 'idade', 'genero', 'pedra 20', 'pedra 21', 'pedra 22', 'pedra 23', 'inde 22', 'inde 23', 'ano_referencia']
cols_24 = ['ra', 'fase_atual', 'idade', 'genero', 'pedra 20', 'pedra 21', 'pedra 22', 'pedra 23', 'inde 22', 'inde 23', 'ano_referencia']

df_pede_24.columns

Index(['ra', 'fase_atual', 'inde 2024', 'pedra 2024', 'idade', 'genero',
       'pedra 20', 'pedra 21', 'pedra 22', 'pedra 23', 'inde 22', 'inde 23',
       'cg', 'cf', 'ct', 'iaa', 'ieg', 'ips', 'ipp', 'ida', 'nota_matematica',
       'nota_portugues', 'nota_ingles', 'indicado_bolsa', 'ipv', 'ian',
       'fase_ideal', 'defasagem', 'ano_referencia'],
      dtype='object')

In [283]:
df_ra_22_23 = pd.merge(df_pede_22[cols_22], df_pede_23[cols_23], on=['ra'], suffixes=("_22","_23"))
df_ra_22_23_24 = pd.merge(df_ra_22_23, df_pede_24[cols_24], on=['ra'], suffixes=("_22_23","_24") )
df_ra_22_23_24.ra.unique()

array(['RA-1', 'RA-2', 'RA-6', 'RA-7', 'RA-12', 'RA-13', 'RA-14', 'RA-17',
       'RA-19', 'RA-21', 'RA-23', 'RA-25', 'RA-26', 'RA-27', 'RA-29',
       'RA-31', 'RA-35', 'RA-36', 'RA-38', 'RA-39', 'RA-40', 'RA-42',
       'RA-45', 'RA-48', 'RA-49', 'RA-52', 'RA-56', 'RA-57', 'RA-58',
       'RA-59', 'RA-62', 'RA-64', 'RA-76', 'RA-78', 'RA-80', 'RA-81',
       'RA-85', 'RA-86', 'RA-87', 'RA-88', 'RA-90', 'RA-91', 'RA-92',
       'RA-93', 'RA-94', 'RA-96', 'RA-98', 'RA-103', 'RA-106', 'RA-107',
       'RA-110', 'RA-111', 'RA-112', 'RA-115', 'RA-116', 'RA-119',
       'RA-121', 'RA-123', 'RA-125', 'RA-127', 'RA-131', 'RA-132',
       'RA-137', 'RA-138', 'RA-143', 'RA-146', 'RA-147', 'RA-149',
       'RA-152', 'RA-153', 'RA-155', 'RA-157', 'RA-158', 'RA-160',
       'RA-161', 'RA-164', 'RA-165', 'RA-166', 'RA-167', 'RA-170',
       'RA-171', 'RA-172', 'RA-173', 'RA-175', 'RA-176', 'RA-178',
       'RA-179', 'RA-180', 'RA-181', 'RA-183', 'RA-184', 'RA-186',
       'RA-187', 'RA-189', 'RA-191', 'RA-192', 'RA-193', 'RA-195',
       'RA-196', 'RA-197', 'RA-199', 'RA-202', 'RA-204', 'RA-211',
       'RA-215', 'RA-217', 'RA-220', 'RA-227', 'RA-229', 'RA-236',
       'RA-237', 'RA-239', 'RA-241', 'RA-242', 'RA-244', 'RA-245',
       'RA-246', 'RA-247', 'RA-249', 'RA-250', 'RA-251', 'RA-260',
       'RA-262', 'RA-267', 'RA-269', 'RA-270', 'RA-271', 'RA-273',
       'RA-274', 'RA-277', 'RA-278', 'RA-279', 'RA-280', 'RA-283',
       'RA-286', 'RA-291', 'RA-299', 'RA-301', 'RA-303', 'RA-304',
       'RA-305', 'RA-306', 'RA-308', 'RA-313', 'RA-315', 'RA-316',
       'RA-318', 'RA-319', 'RA-320', 'RA-321', 'RA-325', 'RA-326',
       'RA-331', 'RA-332', 'RA-336', 'RA-338', 'RA-339', 'RA-340',
       'RA-342', 'RA-346', 'RA-347', 'RA-352', 'RA-356', 'RA-357',
       'RA-359', 'RA-360', 'RA-363', 'RA-364', 'RA-365', 'RA-367',
       'RA-368', 'RA-369', 'RA-375', 'RA-376', 'RA-377', 'RA-381',
       'RA-382', 'RA-383', 'RA-384', 'RA-387', 'RA-388', 'RA-389',
       'RA-390', 'RA-392', 'RA-395', 'RA-397', 'RA-398', 'RA-401',
       'RA-402', 'RA-403', 'RA-404', 'RA-407', 'RA-408', 'RA-409',
       'RA-411', 'RA-412', 'RA-414', 'RA-416', 'RA-417', 'RA-418',
       'RA-419', 'RA-420', 'RA-421', 'RA-422', 'RA-423', 'RA-424',
       'RA-425', 'RA-426', 'RA-428', 'RA-432', 'RA-433', 'RA-434',
       'RA-438', 'RA-442', 'RA-444', 'RA-445', 'RA-450', 'RA-454',
       'RA-456', 'RA-457', 'RA-458', 'RA-459', 'RA-461', 'RA-464',
       'RA-466', 'RA-467', 'RA-469', 'RA-470', 'RA-471', 'RA-472',
       'RA-474', 'RA-476', 'RA-479', 'RA-480', 'RA-483', 'RA-484',
       'RA-487', 'RA-490', 'RA-491', 'RA-493', 'RA-494', 'RA-496',
       'RA-497', 'RA-499', 'RA-500', 'RA-501', 'RA-502', 'RA-503',
       'RA-508', 'RA-509', 'RA-513', 'RA-514', 'RA-516', 'RA-517',
       'RA-518', 'RA-521', 'RA-522', 'RA-524', 'RA-526', 'RA-527',
       'RA-528', 'RA-529', 'RA-530', 'RA-531', 'RA-534', 'RA-535',
       'RA-536', 'RA-538', 'RA-539', 'RA-542', 'RA-543', 'RA-546',
       'RA-547', 'RA-548', 'RA-549', 'RA-555', 'RA-556', 'RA-557',
       'RA-558', 'RA-559', 'RA-562', 'RA-563', 'RA-568', 'RA-570',
       'RA-571', 'RA-573', 'RA-576', 'RA-577', 'RA-578', 'RA-580',
       'RA-581', 'RA-583', 'RA-584', 'RA-586', 'RA-587', 'RA-588',
       'RA-590', 'RA-591', 'RA-592', 'RA-594', 'RA-597', 'RA-599',
       'RA-600', 'RA-601', 'RA-602', 'RA-603', 'RA-604', 'RA-605',
       'RA-606', 'RA-607', 'RA-608', 'RA-610', 'RA-612', 'RA-613',
       'RA-614', 'RA-616', 'RA-618', 'RA-620', 'RA-623', 'RA-624',
       'RA-626', 'RA-628', 'RA-629', 'RA-630', 'RA-631', 'RA-632',
       'RA-633', 'RA-636', 'RA-637', 'RA-638', 'RA-639', 'RA-642',
       'RA-643', 'RA-645', 'RA-646', 'RA-649', 'RA-651', 'RA-652',
       'RA-653', 'RA-655', 'RA-656', 'RA-657', 'RA-658', 'RA-662',
       'RA-663', 'RA-664', 'RA-665', 'RA-666', 'RA-667', 'RA-669',
       'RA-670', 'RA-672', 'RA-680', 'RA-681', 'RA-684', 'RA-686',
       'RA-687', 'RA-688', 'RA-690', 'RA-693', 'RA-696', 'RA-698',
       'RA-699', 'RA-700', 'RA-702', 'RA-704', 'RA-705', 'RA-706',
       'RA-707', 'RA-709', 'RA-710', 'RA-712', 'RA-713', 'RA-714',
       'RA-715', 'RA-716', 'RA-718', 'RA-719', 'RA-721', 'RA-725',
       'RA-727', 'RA-729', 'RA-730', 'RA-731', 'RA-733', 'RA-735',
       'RA-737', 'RA-738', 'RA-740', 'RA-741', 'RA-743', 'RA-745',
       'RA-746', 'RA-747', 'RA-748', 'RA-749', 'RA-750', 'RA-752',
       'RA-753', 'RA-754', 'RA-755', 'RA-756', 'RA-757', 'RA-760',
       'RA-761', 'RA-762', 'RA-763', 'RA-764', 'RA-767', 'RA-768',
       'RA-769', 'RA-770', 'RA-771', 'RA-773', 'RA-774', 'RA-776',
       'RA-777', 'RA-778', 'RA-780', 'RA-781', 'RA-782', 'RA-784',
       'RA-785', 'RA-787', 'RA-788', 'RA-789', 'RA-790', 'RA-792',
       'RA-794', 'RA-795', 'RA-796', 'RA-797', 'RA-798', 'RA-799',
       'RA-801', 'RA-802', 'RA-805', 'RA-806', 'RA-807', 'RA-808',
       'RA-810', 'RA-814', 'RA-816', 'RA-819', 'RA-820', 'RA-822',
       'RA-826', 'RA-827', 'RA-829', 'RA-830', 'RA-831', 'RA-832',
       'RA-833', 'RA-834', 'RA-836', 'RA-837', 'RA-840', 'RA-841',
       'RA-842', 'RA-847', 'RA-850', 'RA-851', 'RA-853', 'RA-854',
       'RA-855', 'RA-858', 'RA-859', 'RA-860'], dtype=object)

In [295]:
df_ra_22_23_24.loc[(~df_ra_22_23_24['pedra 20'].isna()) & (~df_ra_22_23_24['pedra 23_24'].isna())].ra.unique()

array(['RA-27', 'RA-38', 'RA-39', 'RA-40', 'RA-42', 'RA-45', 'RA-48',
       'RA-52', 'RA-56', 'RA-57', 'RA-58', 'RA-64', 'RA-78', 'RA-80',
       'RA-81', 'RA-90', 'RA-91', 'RA-92', 'RA-94', 'RA-103', 'RA-106',
       'RA-107', 'RA-110', 'RA-111', 'RA-112', 'RA-115', 'RA-116',
       'RA-123', 'RA-131', 'RA-132', 'RA-137', 'RA-138', 'RA-143',
       'RA-153', 'RA-157', 'RA-158', 'RA-161', 'RA-164', 'RA-165',
       'RA-166', 'RA-167', 'RA-170', 'RA-173', 'RA-175', 'RA-176',
       'RA-178', 'RA-180', 'RA-181', 'RA-184', 'RA-186', 'RA-187',
       'RA-189', 'RA-191', 'RA-193', 'RA-195', 'RA-196', 'RA-202',
       'RA-204', 'RA-241', 'RA-242', 'RA-244', 'RA-245', 'RA-249',
       'RA-251', 'RA-260', 'RA-270', 'RA-273', 'RA-274', 'RA-278',
       'RA-279', 'RA-283', 'RA-299', 'RA-301', 'RA-303', 'RA-304',
       'RA-305', 'RA-308', 'RA-318', 'RA-331', 'RA-332', 'RA-336',
       'RA-338', 'RA-339', 'RA-340', 'RA-347', 'RA-352', 'RA-356',
       'RA-359', 'RA-360', 'RA-364', 'RA-367', 'RA-368', 'RA-375',
       'RA-376', 'RA-381', 'RA-382', 'RA-383', 'RA-384', 'RA-387',
       'RA-388', 'RA-389', 'RA-395', 'RA-397', 'RA-402', 'RA-403',
       'RA-404', 'RA-411', 'RA-412', 'RA-416', 'RA-418', 'RA-419',
       'RA-420', 'RA-432', 'RA-444', 'RA-454', 'RA-458', 'RA-459',
       'RA-461', 'RA-470', 'RA-471', 'RA-474', 'RA-476', 'RA-479',
       'RA-483', 'RA-487', 'RA-493', 'RA-496', 'RA-497', 'RA-499',
       'RA-500', 'RA-503', 'RA-509', 'RA-516', 'RA-517', 'RA-524',
       'RA-529', 'RA-530', 'RA-535', 'RA-536', 'RA-542', 'RA-547',
       'RA-548', 'RA-555', 'RA-556', 'RA-557', 'RA-563', 'RA-568',
       'RA-570', 'RA-571', 'RA-573', 'RA-578', 'RA-580', 'RA-581',
       'RA-583', 'RA-584', 'RA-590', 'RA-592', 'RA-602', 'RA-613',
       'RA-616', 'RA-618', 'RA-633', 'RA-638', 'RA-646', 'RA-649',
       'RA-655', 'RA-656', 'RA-680', 'RA-707', 'RA-710', 'RA-712',
       'RA-714', 'RA-731', 'RA-750'], dtype=object)

In [297]:
ra = 'RA-39'
display(df_pede_22.loc[df_pede_22.ra == ra][cols_22])
display(df_pede_23.loc[df_pede_23.ra == ra][cols_23])
display(df_pede_24.loc[df_pede_24.ra == ra][cols_24])

,ra,fase_atual,idade,genero,pedra 20,pedra 21,pedra 22,inde 22,ano_referencia
38,RA-39,6,16,Menina,Ametista,Ametista,Ágata,6.033,2022

,ra,fase_atual,idade,genero,pedra 20,pedra 21,pedra 22,pedra 23,inde 22,inde 23,ano_referencia
937,RA-39,FASE 7,17,Feminino,Ametista,Ametista,Ágata,NaN,6.033,NaN,2023

,ra,fase_atual,idade,genero,pedra 20,pedra 21,pedra 22,pedra 23,inde 22,inde 23,ano_referencia
1117,RA-39,8F,18,Feminino,Ametista,Ametista,Ágata,Topázio,6.032564,8.710333,2024

In [275]:
df_pede_23[['pedra 2023','inde 2023']].value_counts()

pedra 2023  inde 2023
Ametista    7.964200     3
Agata       6.964700     2
            6.780000     2
Topázio     8.271200     2
            8.988867     2
                        ..
            9.258700     1
            9.290200     1
            9.310950     1
            9.323700     1
Agata       6.009200     1
Name: count, Length: 925, dtype: int64

In [223]:
cols_22 = set(df_pede_22.columns)
cols_23 = set(df_pede_23.columns)
cols_24 = set(df_pede_24.columns)

cols_comuns = cols_22 & cols_23 & cols_24
print(sorted(cols_comuns))
print("Colunas comuns:",len(cols_comuns))

cols_todas = cols_22 | cols_23 | cols_24
cols_nao_comuns = cols_todas - cols_comuns

print(sorted(cols_nao_comuns))
print("Colunas incomum:",len(cols_nao_comuns))

['ano_referencia', 'cf', 'cg', 'ct', 'fase', 'fase ideal', 'gênero', 'iaa', 'ian', 'ida', 'ieg', 'inde 22', 'indicado', 'ips', 'ipv', 'pedra 20', 'pedra 21', 'pedra 22', 'ra']
Colunas comuns: 19
['defas', 'defasagem', 'idade', 'idade 22', 'inde 2023', 'inde 2024', 'inde 23', 'ing', 'inglês', 'ipp', 'mat', 'matem', 'pedra 2023', 'pedra 2024', 'pedra 23', 'por', 'portug']
Colunas incomum: 17

In [224]:
df_cols = pd.DataFrame({
    'coluna': list(cols_todas),
    '2022': [col in cols_22 for col in cols_todas],
    '2023': [col in cols_23 for col in cols_todas],
    '2024': [col in cols_24 for col in cols_todas],
})

df_cols.sort_values('coluna', inplace=True)

#df_cols[~df_cols[['2022', '2023', '2024']].all(axis=1)]
df_cols.tail(60)

            coluna   2022   2023   2024
11  ano_referencia   True   True   True
15              cf   True   True   True
19              cg   True   True   True
29              ct   True   True   True
26           defas   True  False  False
24       defasagem  False   True   True
32            fase   True   True   True
7       fase ideal   True   True   True
8           gênero   True   True   True
21             iaa   True   True   True
0              ian   True   True   True
17             ida   True   True   True
1            idade  False   True   True
14        idade 22   True  False  False
13             ieg   True   True   True
33       inde 2023  False   True  False
28       inde 2024  False  False   True
34         inde 22   True   True   True
35         inde 23  False   True   True
6         indicado   True   True   True
20             ing  False   True   True
12          inglês   True  False  False
3              ipp  False   True   True
4              ips   True   True   True
16             ipv   True   True   True
22             mat  False   True   True
27           matem   True  False  False
25        pedra 20   True   True   True
18      pedra 2023  False   True  False
5       pedra 2024  False  False   True
9         pedra 21   True   True   True
10        pedra 22   True   True   True
30        pedra 23  False   True   True
23             por  False   True   True
2           portug   True  False  False
31              ra   True   True   True